### ISSUE TITLE
Pictures and link problems

### ISSUE THREAD

**Issue by anlava** [mcoughlin/ztf_summer_school_2022#8]
Pictures are not displayed in the notebook '**lecture01.ipynb**' in sections '**Curse of Dimensionality**', '**Simple Example**' and '**Simulated annealing**'. Also link [The Fallacy of Placing Confidence in Confidence Intervals](http://learnbayes.org/papers/confidenceIntervalsFallacy/) from section '**Parameter Uncertainties**' seems not valid anymore.

Sorry if it's already been reported!

<img width="865" alt="Снимок экрана 2022-07-26 в 15 01 42" src="https://user-images.githubusercontent.com/44841340/181001423-4ec9485b-8ac1-49e8-ad98-997bf9c5d8f4.png">

**Comment by mcoughlin** [comment]
@anlava Thanks for flagging. I think we have now updated the lectures and added the files!
